# Generated by Django 4.2.3 on 2023-07-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('boleta', models.IntegerField(max_length=50, unique=True, verbose_name='Boleta')),
                ('semestre', models.IntegerField(max_length=50, verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'student',
                'ordering': ['semestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50, unique=True, verbose_name='Programa Academico')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'career',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=50, verbose_name='Numero de Computadora')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de computadora')),
                ('laboratorio', models.IntegerField(max_length=2, verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name': 'Computadora',
                'verbose_name_plural': 'Computadoras',
                'db_table': 'computer',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('usuario', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('contrasenia', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
                'db_table': 'manager',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('boleta', models.IntegerField(max_length=50, unique=True, verbose_name='Boleta')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'teacher',
                'ordering': ['id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Sesión')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_final', models.TimeField(verbose_name='Hora final')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computacion.alumno', verbose_name='Alumno')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computacion.encargado', verbose_name='Encargado')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Computacion.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'session',
                'ordering': ['id', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Titulo')),
                ('descripcion', models.TextField(max_length=2000, verbose_name='Descripcion')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora del Reporte')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del Reporte')),
                ('seguimiento', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Seguimiento')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computacion.encargado', verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'report',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computacion.carrera', verbose_name='Carrera'),
        ),
    ]
