# Generated by Django 4.2.3 on 2023-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='qr',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='QR'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='cod_cpu',
            field=models.CharField(max_length=100, null=True, verbose_name='Codigo CPU'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='cod_monitor',
            field=models.CharField(max_length=100, null=True, verbose_name='Codigo Monitor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='qr',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='QR'),
        ),
    ]
