# Generated by Django 4.2.3 on 2023-08-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Computacion', '0002_alumno_qr_computadora_cod_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='computadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Computacion.computadora', verbose_name='Computadora'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='computadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Computacion.computadora', verbose_name='Computadora'),
        ),
    ]
