# Generated by Django 4.2.3 on 2023-08-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computacion', '0003_reportes_computadora_sesion_computadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='boleta',
            field=models.IntegerField(unique=True, verbose_name='Boleta'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='laboratorio',
            field=models.IntegerField(verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='numero',
            field=models.IntegerField(verbose_name='Numero de Computadora'),
        ),
    ]
