# Generated by Django 4.2.3 on 2023-08-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computacion', '0004_alter_alumno_boleta_alter_alumno_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='boleta',
            field=models.IntegerField(unique=True, verbose_name='Boleta'),
        ),
    ]
