# Generated by Django 4.2.3 on 2023-09-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computacion', '0005_alter_profesor_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='computadora',
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='computadora',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Computadora',
        ),
        migrations.DeleteModel(
            name='Encargado',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Reportes',
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
    ]
