# Generated by Django 3.2.19 on 2023-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Computacion', '0008_auto_20230908_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('laboratorio', models.IntegerField()),
                ('cod_monitor', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_cpu', models.CharField(blank=True, max_length=150, null=True)),
                ('ocupada', models.IntegerField()),
            ],
            options={
                'db_table': 'computadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=40)),
                ('apellido_m', models.CharField(max_length=40)),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=25, unique=True)),
                ('contrasenia', models.CharField(max_length=25)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'encargado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=40)),
                ('apellido_m', models.CharField(max_length=40)),
                ('boleta', models.IntegerField(unique=True)),
                ('grupo', models.CharField(blank=True, max_length=10, null=True)),
                ('qr', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=40)),
                ('apellido_m', models.CharField(max_length=40)),
                ('boleta', models.IntegerField(unique=True)),
                ('qr', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
                ('hora', models.DateTimeField()),
                ('fecha', models.DateField()),
                ('seguimiento', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_final', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sesion',
                'managed': False,
            },
        ),
    ]
